_base_: 25_full_minus_b3.yaml

experiment_name: ct25_full_minus_b3_full_scratch_seed42
path: /home/lishengjie/data/nuscenes
version: v1.0-trainval
train_split: train_track
val_split: val
test_split: val
batch_size: 16
workers: 12
epoch: 60
